version: '3.7'
services:
  rabbitweb:
    container_name: rabbitweb
    image: fabtesta/lvr-rabbit-federation-locale-web
    restart: always
    hostname: rabbitweb
    environment:
      - RABBITMQ_FEDERATED_HOST=rabbitlocal
      - RABBITMQ_FEDERATION_UPSTREAM_NAME=fromLocalToWeb
      - RABBITMQ_FEDERATION_POLICY_PATTERN=LVR.
    #volumes:
      #- rabbitweb_data:/var/lib/rabbitmq
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"

  rabbitlocal:
    container_name: rabbitlocal
    image: fabtesta/lvr-rabbit-federation-locale-web
    restart: always
    hostname: rabbitlocal
    environment:
      - RABBITMQ_FEDERATED_HOST=rabbitweb
      - RABBITMQ_FEDERATION_UPSTREAM_NAME=fromWebToLocal
      - RABBITMQ_FEDERATION_POLICY_PATTERN=LVR.
    #volumes:
      #- rabbitlocal_data:/var/lib/rabbitmq
    ports:
      - "15673:15671"
      - "15674:15672"
      - "5673:5671"
      - "5674:5672"

volumes:
  rabbitweb_data:
  rabbitlocal_data:
